import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional
from urllib.parse import parse_qsl, urlparse

import requests

from app.services.cookie_manager import CookieConfigManager

logger = logging.getLogger(__name__)

DEFAULT_BILIBILI_COOKIES_FILE = "config/bilibili.cookies.txt"


class BilibiliCookieService:
    def __init__(self, cookie_manager: Optional[CookieConfigManager] = None):
        self.cookie_manager = cookie_manager or CookieConfigManager()

    @staticmethod
    def resolve_cookie_file_path() -> Path:
        cookies_path = Path(os.getenv("BILIBILI_COOKIES_FILE", DEFAULT_BILIBILI_COOKIES_FILE))
        if not cookies_path.is_absolute():
            cookies_path = Path(__file__).parent.parent.parent / cookies_path
        cookies_path.parent.mkdir(parents=True, exist_ok=True)
        return cookies_path

    @staticmethod
    def _to_iso_time(timestamp: Optional[float]) -> Optional[str]:
        if not timestamp:
            return None
        return datetime.fromtimestamp(timestamp, tz=timezone.utc).isoformat()

    @staticmethod
    def _is_cookie_line(line: str) -> bool:
        stripped = line.strip()
        return bool(stripped and not stripped.startswith("#"))

    @staticmethod
    def _cookies_from_netscape_file(cookies_file: Path) -> Dict[str, str]:
        cookie_map: Dict[str, str] = {}
        if not cookies_file.exists():
            return cookie_map
        try:
            lines = cookies_file.read_text(encoding="utf-8", errors="ignore").splitlines()
        except Exception:
            return cookie_map

        for raw_line in lines:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("#HttpOnly_"):
                line = line[len("#HttpOnly_"):]
            elif line.startswith("#"):
                continue

            parts = line.split("\t")
            if len(parts) < 7:
                parts = line.split()
                if len(parts) < 7:
                    continue

            name = parts[-2].strip()
            value = parts[-1].strip()
            if not name:
                continue
            cookie_map[name] = value
        return cookie_map

    def _cookie_file_has_entries(self, cookies_file: Path) -> bool:
        if not cookies_file.exists():
            return False
        try:
            content = cookies_file.read_text(encoding="utf-8")
            return any(self._is_cookie_line(line) for line in content.splitlines())
        except Exception:
            return False

    def _get_cookie_file_mtime(self, cookies_file: Path) -> Optional[str]:
        if not cookies_file.exists():
            return None
        try:
            return self._to_iso_time(cookies_file.stat().st_mtime)
        except Exception:
            return None

    @staticmethod
    def _best_effort_set_secure_permissions(cookies_file: Path) -> None:
        if os.name == "nt":
            return
        try:
            os.chmod(cookies_file, 0o600)
        except Exception as exc:
            logger.warning(f"设置 cookies 文件权限失败（已忽略）: {exc}")

    @staticmethod
    def parse_cookie_string(cookie_text: Optional[str]) -> Dict[str, str]:
        cookie_map: Dict[str, str] = {}
        if not cookie_text:
            return cookie_map

        for chunk in cookie_text.split(";"):
            part = chunk.strip()
            if not part or "=" not in part:
                continue
            key, value = part.split("=", 1)
            key = key.strip()
            value = value.strip()
            if not key:
                continue
            cookie_map[key] = value
        return cookie_map

    @staticmethod
    def parse_cookie_from_url(login_url: Optional[str]) -> Dict[str, str]:
        if not login_url:
            return {}
        parsed = urlparse(login_url)
        return {k: v for k, v in parse_qsl(parsed.query, keep_blank_values=True)}

    @staticmethod
    def to_cookie_string(cookie_map: Dict[str, str]) -> str:
        return "; ".join([f"{key}={value}" for key, value in cookie_map.items() if key and value is not None])

    @staticmethod
    def merge_cookie_map(*cookie_maps: Dict[str, str]) -> Dict[str, str]:
        merged: Dict[str, str] = {}
        for cookie_map in cookie_maps:
            for key, value in (cookie_map or {}).items():
                if value is None:
                    continue
                merged[key] = str(value)
        return merged

    @staticmethod
    def write_cookie_file(cookie_map: Dict[str, str], cookies_file: Path) -> None:
        expires = str(int(time.time()) + 365 * 24 * 3600)
        lines = [
            "# Netscape HTTP Cookie File",
            "# This file is generated by BiliNote for yt-dlp subtitle access.",
            "",
        ]

        for key, value in cookie_map.items():
            if not key or value is None:
                continue
            lines.append(f".bilibili.com\tTRUE\t/\tFALSE\t{expires}\t{key}\t{value}")

        temp_path = cookies_file.with_suffix(".tmp")
        temp_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        temp_path.replace(cookies_file)
        BilibiliCookieService._best_effort_set_secure_permissions(cookies_file)

    def migrate_legacy_cookie_if_needed(self) -> Dict[str, Any]:
        cookies_file = self.resolve_cookie_file_path()
        if self._cookie_file_has_entries(cookies_file):
            return {
                "migrated": False,
                "source": "cookies_file",
                "cookies_file": str(cookies_file),
                "exists": True,
                "updated_at": self._get_cookie_file_mtime(cookies_file),
            }

        legacy_cookie = self.cookie_manager.get("bilibili")
        if not legacy_cookie:
            return {
                "migrated": False,
                "source": "missing",
                "cookies_file": str(cookies_file),
                "exists": False,
                "updated_at": None,
            }

        legacy_cookie_map = self.parse_cookie_string(legacy_cookie)
        if not legacy_cookie_map:
            self.cookie_manager.delete("bilibili")
            return {
                "migrated": False,
                "source": "legacy_invalid",
                "cookies_file": str(cookies_file),
                "exists": False,
                "updated_at": None,
            }

        self.write_cookie_file(legacy_cookie_map, cookies_file)
        self.cookie_manager.delete("bilibili")
        logger.info("已将 legacy downloader.json 中的 B站 Cookie 迁移至 cookies.txt")
        return {
            "migrated": True,
            "source": "legacy_migrated",
            "cookies_file": str(cookies_file),
            "exists": True,
            "updated_at": self._get_cookie_file_mtime(cookies_file),
        }

    def get_cookie_status(self) -> Dict[str, Any]:
        migration = self.migrate_legacy_cookie_if_needed()
        cookies_file = self.resolve_cookie_file_path()
        exists = self._cookie_file_has_entries(cookies_file)
        return {
            "exists": exists,
            "cookies_file": str(cookies_file),
            "updated_at": self._get_cookie_file_mtime(cookies_file),
            "source": migration.get("source") if migration else ("cookies_file" if exists else "missing"),
        }

    def verify_cookie(self) -> Dict[str, Any]:
        status = self.get_cookie_status()
        if not status.get("exists"):
            return {
                "valid": False,
                "checked_at": self._to_iso_time(time.time()),
                "message": "未检测到可用 Cookie 文件",
                "error": "COOKIE_MISSING",
            }

        cookies_file = self.resolve_cookie_file_path()
        cookie_map = self._cookies_from_netscape_file(cookies_file)
        if not cookie_map:
            return {
                "valid": False,
                "checked_at": self._to_iso_time(time.time()),
                "message": "Cookie 文件为空或格式无效",
                "error": "COOKIE_INVALID",
            }

        cookie_text = self.to_cookie_string(cookie_map)
        headers = {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            ),
            "Referer": "https://www.bilibili.com/",
            "Cookie": cookie_text,
        }
        try:
            response = requests.get(
                "https://api.bilibili.com/x/web-interface/nav",
                headers=headers,
                timeout=10,
            )
            response.raise_for_status()
            payload = response.json()
        except Exception as exc:
            logger.warning(f"验证 B站 Cookie 请求失败: {exc}")
            return {
                "valid": False,
                "checked_at": self._to_iso_time(time.time()),
                "message": f"Cookie 验证请求失败: {exc}",
                "error": "VERIFY_REQUEST_FAILED",
            }

        data = payload.get("data") if isinstance(payload, dict) else {}
        is_login = bool(data.get("isLogin")) if isinstance(data, dict) else False
        uname = data.get("uname") if isinstance(data, dict) else None
        level_info = data.get("level_info") if isinstance(data, dict) else None

        return {
            "valid": is_login,
            "checked_at": self._to_iso_time(time.time()),
            "message": "Cookie 有效，可访问登录态接口" if is_login else "Cookie 无效或已过期，请重新登录",
            "uname": uname,
            "level": level_info.get("current_level") if isinstance(level_info, dict) else None,
            "bili_code": payload.get("code") if isinstance(payload, dict) else None,
        }

    def clear_cookie(self) -> Dict[str, Any]:
        cookies_file = self.resolve_cookie_file_path()
        existed = cookies_file.exists()
        if cookies_file.exists():
            cookies_file.unlink()
        self.cookie_manager.delete("bilibili")
        return {
            "cleared": existed,
            "exists": False,
            "cookies_file": str(cookies_file),
            "updated_at": None,
            "source": "cleared",
        }

    def persist_bilibili_cookie(
        self,
        cookie_text: Optional[str] = None,
        cookie_map: Optional[Dict[str, str]] = None,
    ) -> Dict[str, Any]:
        parsed_cookie_map = self.parse_cookie_string(cookie_text)
        merged_cookie_map = self.merge_cookie_map(parsed_cookie_map, cookie_map or {})
        if not merged_cookie_map:
            raise ValueError("未获取到可保存的 B 站 Cookie")

        cookies_file = self.resolve_cookie_file_path()
        self.write_cookie_file(merged_cookie_map, cookies_file)
        self.cookie_manager.delete("bilibili")

        logger.info(f"B站 Cookie 已保存到文件: {cookies_file}")
        return {
            "cookie_saved": True,
            "cookies_file": str(cookies_file),
            "updated_at": self._get_cookie_file_mtime(cookies_file),
            "source": "manual_or_qr",
        }
